name: "S3 Sync"
description: "Sync a directory to an AWS S3 repository with correct content type for br and gzip files"
author: hexlabsio
runs:
  using: docker
  image: Dockerfile
branding:
  icon: refresh-cw
  color: green
